project:
  type: website
  output-dir: public

website:
  title: "Quarto interactive presentation"
  navbar:
    search: true

format:
  html:
    theme: lux
    mainfont: "Roboto Light"

language: 
  search-text-placeholder: "Search a presentation"

extensions:
  - vertical.lua
  - molstar.lua

