project:
  type: website
  output-dir: public

website:
  title: "Quarto interactive presentation"

format:
  html:
    theme: lux

language: 
  search-text-placeholder: "Search a presentation"

extensions:
  - vertical.lua

